
volumes:
  minio:
  db:

networks:
  iwai:

services:
  minio:
    image: bitnami/minio:2024.11.7-debian-12-r0
    container_name: ${PROJECT}-${ENVIRONMENT}-minio
    ports:
      - ${PORT_MINIO}:9000
      - ${PORT_MINIO_CONSOLE}:9001
    networks:
      - iwai
    volumes:
      - minio:/bitnami/minio/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
  
  db:
    image: bitnami/postgresql:16.4.0-debian-12-r23
    container_name: ${PROJECT}-${ENVIRONMENT}-pg
    networks:
      - iwai
    volumes:
      - db:/bitnami/postgresql
    ports:
      - ${PORT_POSTGRESQL}:5432
    environment:
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
    